// src/adapters/vue/example.vue
<template>
  <div class="app">
    <!-- Header with categorized elements -->
    <header class="header">
      <h1>My Vue App</h1>
      
      <!-- Always visible basic button -->
      <UIFlowElement category="basic" area="header">
        <button>Save</button>
      </UIFlowElement>
      
      <!-- Advanced export button -->
      <UIFlowElement 
        category="advanced" 
        area="header"
        help-text="Export your data in various formats"
        :is-new="true"
      >
        <button>Export</button>
      </UIFlowElement>
      
      <!-- Expert-level batch operations -->
      <UIFlowElement 
        category="expert" 
        area="header"
        help-text="Bulk operations for power users"
      >
        <button>Batch Operations</button>
      </UIFlowElement>
      
      <!-- Density indicator -->
      <UIFlowDensityIndicator area="header" />
    </header>

    <!-- Main content area -->
    <main class="main-content">
      <h2>Editor (Density: {{ Math.round(editorDensity * 100) }}%)</h2>
      
      <!-- Basic text editing always available -->
      <UIFlowElement category="basic" area="editor">
        <textarea placeholder="Start typing..."></textarea>
      </UIFlowElement>
      
      <!-- Conditional formatting toolbar -->
      <UIFlowConditional area="editor" :min-density="0.3">
        <div class="formatting-toolbar">
          <UIFlowElement category="advanced" area="editor">
            <button>Bold</button>
          </UIFlowElement>
          
          <UIFlowElement category="advanced" area="editor">
            <button>Italic</button>
          </UIFlowElement>
          
          <UIFlowElement category="expert" area="editor">
            <button>Insert Table</button>
          </UIFlowElement>
        </div>
      </UIFlowConditional>
      
      <!-- Expert features only at high density -->
      <UIFlowConditional area="editor" :min-density="0.7">
        <AdvancedEditor />
      </UIFlowConditional>
    </main>

    <!-- Sidebar with controls -->
    <aside class="sidebar">
      <h3>Controls</h3>
      
      <UIFlowElement category="basic" area="sidebar">
        <button @click="simulateBeginner">
          Simulate Beginner Usage
        </button>
      </UIFlowElement>
      
      <UIFlowElement category="advanced" area="sidebar">
        <button @click="simulateExpert">
          Simulate Expert Usage
        </button>
      </UIFlowElement>
      
      <UIFlowElement 
        category="expert" 
        area="sidebar"
        help-text="Highlight features for user education"
      >
        <button @click="highlightFeature">
          Highlight Feature
        </button>
      </UIFlowElement>
      
      <!-- Manual density controls -->
      <UIFlowConditional area="sidebar" :min-density="0.5">
        <DensityControls />
      </UIFlowConditional>
    </aside>
  </div>
</template>

<script setup>
import { onMounted } from 'vue';
import { 
  createUIFlow, 
  provideUIFlow, 
  useUIFlow,
  useAreaDensity,
  useUIFlowHighlight,
  useUIFlowEvents,
  UIFlowElement,
  UIFlowConditional,
  UIFlowDensityIndicator
} from './index.js';
import AdvancedEditor from './components/AdvancedEditor.vue';
import DensityControls from './components/DensityControls.vue';

// Create and provide UIFlow instance
const config = {
  userId: 'user-123',
  categories: ['basic', 'advanced', 'expert'],
  learningRate: 0.1,
  dataSources: {
    api: { 
      endpoint: 'https://api.example.com', 
      primary: true 
    }
  }
};

const uiflowInstance = createUIFlow(config);
provideUIFlow(uiflowInstance);

// Initialize UIFlow
onMounted(() => {
  uiflowInstance.initialize();
});

// Use UIFlow composables
const { uiflow } = useUIFlow();
const { density: editorDensity } = useAreaDensity('editor');
const { flagAsNew } = useUIFlowHighlight();

// Listen to UIFlow events
useUIFlowEvents({
  'adaptation': (detail) => {
    console.log('Density adapted:', detail);
  },
  'sync-success': (detail) => {
    console.log('Synced with data sources:', detail);
  }
});

// Methods
const simulateBeginner = () => {
  if (uiflow.value) {
    const interactions = Array(20).fill({ category: 'basic' });
    uiflow.value.simulateUsage('editor', interactions, 7);
  }
};

const simulateExpert = () => {
  if (uiflow.value) {
    const interactions = [
      ...Array(5).fill({ category: 'basic' }),
      ...Array(10).fill({ category: 'advanced' }),
      ...Array(15).fill({ category: 'expert' })
    ];
    uiflow.value.simulateUsage('editor', interactions, 7);
  }
};

const highlightFeature = () => {
  const advancedButton = document.querySelector('[data-uiflow-category="advanced"]');
  if (advancedButton) {
    const elementId = advancedButton.getAttribute('data-uiflow-id');
    flagAsNew(elementId, 'Try this advanced feature!', 5000);
  }
};
</script>

<style scoped>
.app {
  display: grid;
  grid-template-areas: 
    "header header"
    "main sidebar";
  grid-template-columns: 1fr 300px;
  grid-template-rows: auto 1fr;
  height: 100vh;
  gap: 1rem;
  padding: 1rem;
}

.header {
  grid-area: header;
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 1rem;
  background: #f3f4f6;
  border-radius: 8px;
}

.main-content {
  grid-area: main;
  padding: 1rem;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.sidebar {
  grid-area: sidebar;
  padding: 1rem;
  background: #f9fafb;
  border-radius: 8px;
}

.formatting-toolbar {
  display: flex;
  gap: 0.5rem;
  margin: 1rem 0;
  padding: 0.5rem;
  background: #f3f4f6;
  border-radius: 4px;
}

textarea {
  width: 100%;
  height: 200px;
  padding: 0.5rem;
  border: 1px solid #d1d5db;
  border-radius: 4px;
  resize: vertical;
}

button {
  padding: 0.5rem 1rem;
  background: #3b82f6;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button:hover {
  background: #2563eb;
}

h1, h2, h3 {
  margin: 0 0 1rem 0;
}
</style>

// src/adapters/react/example.jsx
/**
 * UIFlow React Adapter - Usage Example
 */

import React from 'react';
import { 
  UIFlowProvider, 
  UIFlowElement, 
  UIFlowConditional,
  UIFlowDensityIndicator,
  useUIFlow,
  useAreaDensity,
  useUIFlowElement,
  useUIFlowHighlight,
  useUIFlowEvents
} from './index.js';

// Example App with UIFlow
function App() {
  const config = {
    userId: 'user-123',
    categories: ['basic', 'advanced', 'expert'],
    learningRate: 0.1,
    dataSources: {
      api: { 
        endpoint: 'https://api.example.com', 
        primary: true 
      }
    }
  };

  return (
    <UIFlowProvider config={config}>
      <div className="app">
        <Header />
        <MainContent />
        <Sidebar />
      </div>
    </UIFlowProvider>
  );
}

// Header with basic and advanced features
function Header() {
  return (
    <header className="header">
      <h1>My App</h1>
      
      {/* Always visible basic button */}
      <UIFlowElement category="basic" area="header">
        <button>Save</button>
      </UIFlowElement>
      
      {/* Advanced export button */}
      <UIFlowElement 
        category="advanced" 
        area="header"
        helpText="Export your data in various formats"
        isNew={true}
      >
        <button>Export</button>
      </UIFlowElement>
      
      {/* Expert-level batch operations */}
      <UIFlowElement 
        category="expert" 
        area="header"
        helpText="Bulk operations for power users"
      >
        <button>Batch Operations</button>
      </UIFlowElement>
      
      {/* Density indicator */}
      <UIFlowDensityIndicator area="header" />
    </header>
  );
}

// Main content area with conditional rendering
function MainContent() {
  const { density } = useAreaDensity('editor');
  
  return (
    <main className="main-content">
      <h2>Editor (Density: {Math.round(density * 100)}%)</h2>
      
      {/* Basic text editing always available */}
      <UIFlowElement category="basic" area="editor">
        <textarea placeholder="Start typing..."></textarea>
      </UIFlowElement>
      
      {/* Conditional rendering based on density */}
      <UIFlowConditional area="editor" minDensity={0.3}>
        <div className="formatting-toolbar">
          <UIFlowElement category="advanced" area="editor">
            <button>Bold</button>
          </UIFlowElement>
          
          <UIFlowElement category="advanced" area="editor">
            <button>Italic</button>
          </UIFlowElement>
          
          <UIFlowElement category="expert" area="editor">
            <button>Insert Table</button>
          </UIFlowElement>
        </div>
      </UIFlowConditional>
      
      {/* Expert features only at high density */}
      <UIFlowConditional area="editor" minDensity={0.7}>
        <AdvancedEditor />
      </UIFlowConditional>
    </main>
  );
}

// Advanced editor component
function AdvancedEditor() {
  const { elementRef, isVisible } = useUIFlowElement('expert', 'editor', {
    helpText: 'Advanced code editor with syntax highlighting'
  });
  
  if (!isVisible) return null;
  
  return (
    <div ref={elementRef} className="advanced-editor">
      <h3>Code Editor</h3>
      <textarea placeholder="// Advanced code editing..."></textarea>
    </div>
  );
}

// Sidebar with event handling
function Sidebar() {
  const { highlight, flagAsNew, showTooltip } = useUIFlowHighlight();
  const { uiflow } = useUIFlow();
  
  // Listen to UIFlow events
  useUIFlowEvents({
    'adaptation': (detail) => {
      console.log('Density adapted:', detail);
    },
    'sync-success': (detail) => {
      console.log('Synced with data sources:', detail);
    }
  });
  
  const handleSimulateBeginner = () => {
    if (uiflow) {
      // Simulate beginner usage pattern
      const interactions = Array(20).fill({ category: 'basic' });
      uiflow.simulateUsage('editor', interactions, 7);
    }
  };
  
  const handleSimulateExpert = () => {
    if (uiflow) {
      // Simulate expert usage pattern
      const interactions = [
        ...Array(5).fill({ category: 'basic' }),
        ...Array(10).fill({ category: 'advanced' }),
        ...Array(15).fill({ category: 'expert' })
      ];
      uiflow.simulateUsage('editor', interactions, 7);
    }
  };
  
  const handleHighlightFeature = () => {
    // Find an advanced feature and highlight it
    const advancedButton = document.querySelector('[data-uiflow-category="advanced"]');
    if (advancedButton) {
      const elementId = advancedButton.getAttribute('data-uiflow-id');
      flagAsNew(elementId, 'Try this advanced feature!', 5000);
    }
  };
  
  return (
    <aside className="sidebar">
      <h3>Controls</h3>
      
      <UIFlowElement category="basic" area="sidebar">
        <button onClick={handleSimulateBeginner}>
          Simulate Beginner Usage
        </button>
      </UIFlowElement>
      
      <UIFlowElement category="advanced" area="sidebar">
        <button onClick={handleSimulateExpert}>
          Simulate Expert Usage
        </button>
      </UIFlowElement>
      
      <UIFlowElement 
        category="expert" 
        area="sidebar"
        helpText="Highlight features for user education"
      >
        <button onClick={handleHighlightFeature}>
          Highlight Feature
        </button>
      </UIFlowElement>
      
      {/* Manual density controls */}
      <UIFlowConditional area="sidebar" minDensity={0.5}>
        <DensityControls />
      </UIFlowConditional>
    </aside>
  );
}

// Manual density controls component
function DensityControls() {
  const { density, setDensityLevel } = useAreaDensity('editor');
  
  return (
    <div className="density-controls">
      <h4>Manual Density Control</h4>
      <input
        type="range"
        min="0"
        max="1"
        step="0.1"
        value={density}
        onChange={(e) => setDensityLevel(parseFloat(e.target.value))}
      />
      <span>{Math.round(density * 100)}%</span>
    </div>
  );
}

export default App;

// Example of custom hook for feature discovery
export function useFeatureDiscovery(area = 'default') {
  const { uiflow } = useUIFlow();
  const { highlight, flagAsNew } = useUIFlowHighlight();
  
  const discoverNewFeatures = React.useCallback(() => {
    if (!uiflow) return;
    
    // Find elements that just became visible
    const elements = document.querySelectorAll(`[data-uiflow-area="${area}"][data-uiflow-visible="true"]`);
    
    elements.forEach(element => {
      const category = element.getAttribute('data-uiflow-category');
      const elementId = element.getAttribute('data-uiflow-id');
      const helpText = element.getAttribute('data-uiflow-help');
      
      if (category !== 'basic' && helpText) {
        flagAsNew(elementId, helpText, 8000);
      }
    });
  }, [uiflow, area, flagAsNew]);
  
  return { discoverNewFeatures };
}
